# Name of your application. Used to uniquely configure containers.
service: lion_social

# Name of the container image.
image: leo-mid/lion_social

# Deploy to these servers.
servers:
  web:
    hosts:
      - 129.21.143.238
    options:
      "add-host": "host.docker.internal:172.20.0.1"


# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: social.lionnav.com
  # Proxy connects to your container on port 80 by default.
  app_port: 5002
  healthcheck:
    path: /up
    interval: 2
    timeout: 5

registry:
  server: localhost:5555

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  # password:
  #   - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    PORT: 5002

# Inject ENV variables into containers (secrets come from .kamal/secrets).
#
# env:
#   clear:
#     DB_HOST: 192.168.0.2
#   secret:
#     - RAILS_MASTER_KEY

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"


# Use a persistent storage volume.
#
# volumes:
#   - "app_storage:/app/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64

  # # Build image via remote server (useful for faster amd64 builds on arm64 computers)
  # remote: ssh://docker@docker-builder-server
  #
  # # Pass arguments and secrets to the Docker build process
  # args:
  #   RUBY_VERSION: 3.4.4
  # secrets:
  #   - GITHUB_TOKEN
  #   - RAILS_MASTER_KEY

boot:
  limit: 1
  wait: 5

# Use a different ssh user than root
ssh:
  user: kamal
  port: 25457
# Use accessory services (secrets come from .kamal/secrets).
#

  # db:
  #   image: mysql:8.0
  #   host: 192.168.0.2
  #   port: 3306
  #   env:
  #     clear:
  #       MYSQL_ROOT_HOST: '%'
  #     secret:
  #       - MYSQL_ROOT_PASSWORD
  #   files:
  #     - config/mysql/production.cnf:/etc/mysql/my.cnf
  #     - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
  #   directories:
  #     - data:/var/lib/mysql

